name: CI

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:

    phpunit:
        name: PHPUnit with PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
        runs-on: ${{ matrix.operating-system }}

        strategy:
            fail-fast: false
            matrix:
                operating-system: [ ubuntu-latest, windows-latest ]
                php: [ '8.1', '8.2', '8.3', '8.4' ]
                symfony: [ '5.4.*', '6.4.*', '7.2.*' ]
                exclude:
                    - { php: '8.1', symfony: '7.2.*' }

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup PHP ${{ matrix.php }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: flex
                  coverage: none

            - name: Install composer dependencies
              uses: ramsey/composer-install@v3
              env:
                  SYMFONY_REQUIRE: ${{ matrix.symfony }}

            - name: Run test suite on PHP ${{ matrix.php }} and Symfony ${{ matrix.symfony }}
              run: vendor/bin/phpunit tests

    ecs:
        name: Easy Coding Standard
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                php-version: latest
            - uses: ramsey/composer-install@v3
            - run: vendor/bin/ecs

    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: latest
            - uses: ramsey/composer-install@v3
            - run: vendor/bin/phpstan
